# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbdemo', '0003_auto_20161119_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointScored', models.IntegerField(default=0)),
                ('passYards', models.IntegerField(default=0)),
                ('rushYards', models.IntegerField(default=0)),
                ('recYards', models.IntegerField(default=0)),
                ('rushTDs', models.IntegerField(default=0)),
                ('recTDs', models.IntegerField(default=0)),
                ('interceptions', models.IntegerField(default=0)),
                ('fumblesLost', models.IntegerField(default=0)),
                ('twoPtConversion', models.IntegerField(default=0)),
                ('passTDs', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Consistency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('eliteScore', models.FloatField(default=0)),
                ('topScore', models.FloatField(default=0)),
                ('subparScore', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Injury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ir', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=5)),
                ('dfy', models.BooleanField(default=False)),
                ('injuryName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Kicker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fg', models.IntegerField(default=0)),
                ('fga', models.IntegerField(default=0)),
                ('xpa', models.IntegerField(default=0)),
                ('xp', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espnRank', models.IntegerField(default=-1)),
                ('nflRank', models.IntegerField(default=-1)),
                ('sugPos', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('experience', models.IntegerField(default=0)),
                ('position', models.CharField(max_length=2)),
                ('teamID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbdemo.Team')),
            ],
        ),
        migrations.CreateModel(
            name='SeasonOffensiveStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointScored', models.IntegerField(default=0)),
                ('passYards', models.IntegerField(default=0)),
                ('rushYards', models.IntegerField(default=0)),
                ('recYards', models.IntegerField(default=0)),
                ('rushTDs', models.IntegerField(default=0)),
                ('recTDs', models.IntegerField(default=0)),
                ('interceptions', models.IntegerField(default=0)),
                ('fumblesLost', models.IntegerField(default=0)),
                ('twoPtConversion', models.IntegerField(default=0)),
                ('passTDs', models.IntegerField(default=0)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbdemo.Players')),
            ],
        ),
        migrations.CreateModel(
            name='Suspended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reasons', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=5)),
                ('susLength', models.IntegerField(default=0)),
                ('dfy', models.BooleanField(default=False)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbdemo.Players')),
            ],
        ),
        migrations.AddField(
            model_name='playerrank',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbdemo.Players'),
        ),
        migrations.AddField(
            model_name='kicker',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbdemo.Players'),
        ),
        migrations.AddField(
            model_name='injury',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbdemo.Players'),
        ),
        migrations.AddField(
            model_name='careerstats',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbdemo.Players'),
        ),
    ]
