# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 05:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbdemo', '0004_auto_20161120_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='defenseID',
        ),
        migrations.AddField(
            model_name='consistency',
            name='pid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbdemo.Players'),
        ),
        migrations.AddField(
            model_name='defense',
            name='teamID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbdemo.Team'),
        ),
    ]
