# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 06:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbdemo', '0005_auto_20161128_0554'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPlayerRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbdemo.Players')),
                ('teamId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbdemo.Team')),
            ],
        ),
    ]
