# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 06:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbdemo', '0006_teamplayerrelation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='teamID',
        ),
    ]
